import type { Metadata } from "next";

import localFont from  "next/font/local"

import "./globals.css";

import Header from "@/app/components/Header"


const localInter =localFont({
  src:'./fonts/inter.ttf'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={localInter.className}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
