# Generated by Django 5.0.1 on 2024-01-19 13:33

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_alter_item_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_match_maker',
            name='giver',
        ),
        migrations.RemoveField(
            model_name='item_match_maker',
            name='item',
        ),
        migrations.RemoveField(
            model_name='item_match_maker',
            name='receiver',
        ),
        migrations.AddField(
            model_name='cash',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cash',
            name='participant',
            field=models.ManyToManyField(blank=True, related_name='cash_participant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cash',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='item',
            name='participant',
            field=models.ManyToManyField(blank=True, related_name='item_participant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cash',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Cash_Match_Maker',
        ),
        migrations.DeleteModel(
            name='Item_Match_Maker',
        ),
    ]
