# Generated by Django 5.0.1 on 2024-01-20 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_item_category_remove_item_participant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giveaway',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
