# Generated by Django 5.0.1 on 2024-01-22 16:20

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_giveaway_created_at_alter_giveaway_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveaway',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title', 'description']),
        ),
    ]
